# server {
    
#     server_name sappp01;
    
#     return 301 http://sappp01:3000$request_uri;
# }

server{
    listen 3000;

	server_name sappp01;
	
    # ssl_stapling off;
    # ssl_stapling_verify off;
    # add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    # add_header X-Frame-Options DENY;
    # add_header X-Content-Type-Options nosniff;
    
    location /static/ {
        alias /var/www/html/static/;
    }

    location / {
        proxy_pass http://techmind:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        }

    location /ws/ {
        proxy_pass http://techmind:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
         proxy_set_header Host $host;
    }

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
}	